name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Desktop app"
    labels:
      - "C-app"
      - "A-EIPs"
  - title: "🌐 Extension"
    labels:
      - "C-extension"
  - title: "🐛 Bug Fixes"
    labels:
      - "B-bugfix"
  - title: "🧰 Maintenance"
    labels:
      - "C-docs"
      - "C-dependencies"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - "breaking-change"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "bugfix"
      - "bug"
  default: patch

include-pre-releases: true

template: |
  ## Changes

  $CHANGES
