name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 New features"
    labels:
      - "A-feature"

  - title: "💥 Breaking changes"
    labels:
      - "B-breaking-change"

  - title: "🐛 Bug Fixes"
    labels:
      - "B-bugfix"

  - title: "🧰 Maintenance"
    collapse-after: 5
    labels:
      - "C-docs"
      - "C-chore"

  - title: "⬆️ Dependencies"
    collapse-after: 5
    labels:
      - "C-dependencies"

exclude-labels:
  - "A-enhancement"
  - "A-refactor"


change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - "B-breaking-change"
  minor:
    labels:
      - "A-feature"
  default: patch

include-pre-releases: true

template: |
  $CHANGES
