name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bugfix"
      - "bug"
  - title: "🌐 Extension"
    labels:
      - "extension"
  - title: "Code Quality"
    labels:
      - "refactor"
      - "enhancement"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "docs"
      - "dependencies"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - "breaking-change"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "bugfix"
      - "bug"
  default: patch

include-pre-releases: true

template: |
  ## Changes

  $CHANGES

  ## Installing

  1. Download the appropriate binary for your architecture, and set it up in your $PATH
  2. Download extension.zip and manually install it in your browser (currently tested on Google Chrome, more to come soon):
    2.1. Extract the zip file
    2.2. go to chrome://extensions
    2.3. enable Developer mode (upper right corner)
    2.4. Load unpacked -> choose the directory you extracted from the ZIP file
  3. Run ethui.
