CREATE TABLE transactions (
  hash VARCHAR PRIMARY KEY COLLATE NOCASE,
  chain_name VARCHAR NOT NULL COLLATE NOCASE,
  from_address VARCHAR NOT NULL COLLATE NOCASE,
  to_address VARCHAR NOT NULL COLLATE NOCASE
);
