[package]
name = "iron-indexer"
version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iron-tracing.workspace = true

tokio.workspace = true
clap.workspace = true
serde.workspace = true
color-eyre.workspace = true
alloy-primitives.workspace = true
tracing.workspace = true
futures.workspace = true

toml = "0.8.8"
actix = "0.13.1"
actix-web = "4"
actix-cors = "0.6.4"

reth-db = { git = "https://github.com/paradigmxyz/reth", package = "reth-db" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", package = "reth-primitives", features = [
  "optimism",
] }
reth_provider = { git = "https://github.com/paradigmxyz/reth", package = "reth-provider" }
reth-rpc-types = { git = "https://github.com/paradigmxyz/reth" }
