[target.x86_64-apple-darwin]
rustflags = [
  "-C",
  "link-arg=-framework",
  "-C",
  "link-arg=IOKit",
  "-C",
  "link-arg=-framework",
  "-C",
  "link-arg=CoreFoundation",
  "-C",
  "link-arg=-lusb-1.0",
]
