[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', "dependencies"]
solc_version = '0.8.27'

[soldeer]
recursive_deps = true

[dependencies]
"@openzeppelin-contracts" = "5.0.2"
forge-std = "1.9.4"
