[package]
name = "iron-http"
version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true

[dependencies]
axum = "0.6"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
