name: CI - Rust

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "./extension/**"
      - "./gui/**"
      - "*.json"
      - "*.md"
      - "LICENSE"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo:
    name: cargo-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies (ubuntu only)
        run: |
          echo {{matrix.platform}}
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: rust cache
        uses: Swatinem/rust-cache@v2

      - name: cargo-check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: cargo-clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all

      - name: cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1
