name: nodejs

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.skip_check.outputs.src }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: skip_check
        with:
          filters: |
            src:
              - ".github/workflows/nodejs.yml"
              - "gui/**"
              - "packages/**"
              - "package.json"
              - "yarn.lock"

  node-lint:
    needs: check-skip
    if: needs.check-skip.outputs.skip == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g yarn
      - uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version: "22"

      - run: yarn install --frozen-lockfile
      - run: cat packages/abiparse/package.json
      - run: yarn lint
      - run: yarn test
