name: nodejs

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.skip_check.outputs.src }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: skip_check
        with:
          filters: |
            src:
              - ".github/workflows/nodejs.yml"
              - "gui/**"
              - "packages/**"
              - "package.json"
              - "pnpm-lock.yaml"

  node-lint:
    needs: check-skip
    if: needs.check-skip.outputs.skip == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: "24.x"

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
