name: Pull request linter

on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled
      - opened
      - reopened
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  enforce-labels:
    uses: ethui/workflows/.github/workflows/pr-lint.yml@main
